version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./output:/app/output  # Maps 'output' directory in current path to '/app/output' in container

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_tasks worker --loglevel=info
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./output:/app/output  # Ensure worker can write to the same 'output' directory

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data  # Persistent volume for Redis data

volumes:
  redis-data:  # Define the volume to be created by Docker
